# -*- coding: utf-8 -*-
"""All in one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiTrOO-D942sVK3i14iQDqSLjw-YLvIo
"""

# =========================================
# 1) Install libraries
# =========================================
!pip install -q transformers datasets setfit torch accelerate

# =========================================
# 2) Zero-shot classification (no training)
# =========================================
from transformers import pipeline

zero_shot = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

text = "The school boy met with a serious accident while crossing the road."
labels = ["positive", "negative", "neutral"]

print("Zero-shot:", zero_shot(text, candidate_labels=labels))

# =========================================
# 3) One-shot via prompt (no training)
# =========================================
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = """Classify sentiment:
Text: I love this movie! -> Positive
Text: The spacyr code was really difficult to debug from scratch ->"""

out = generator(prompt, max_length=60, do_sample=False)
print("One-shot (prompt continuation):\n", out[0]["generated_text"])

# ============================
# 1. Install Required Libraries
# ============================
!pip install -q transformers datasets setfit torch accelerate scikit-learn

# ============================
# 2. Few-Shot Training with SetFit v2
# ============================
from setfit import SetFitModel, Trainer, TrainingArguments
from datasets import Dataset
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Load pretrained Sentence Transformer backbone
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")

# Tiny few-shot dataset (3 examples per class)
train_dataset = Dataset.from_dict({
    "text": [
        "I love this!", "This is bad.", "Amazing performance!",
        "Terrible experience", "Okay, not great", "Pretty good overall"
    ],
    "label": [1, 0, 1, 0, 0, 1]  # 1=Positive, 0=Negative
})

# TrainingArguments (new API)
args = TrainingArguments(
    output_dir="checkpoints",
    batch_size=(16, 2),     # (body_batch_size, head_batch_size)
    num_epochs=(1, 16),     # (body_epochs, head_epochs)
    num_iterations=20,      # contrastive pair iterations
    body_learning_rate=2e-5,
    head_learning_rate=1e-2,
    use_amp=False
)

trainer = Trainer(
    model=model,
    train_dataset=train_dataset,
    args=args
)

# Train
trainer.train()

# Quick test predictions
preds = trainer.model([
    "The movie was boring",
    "Fantastic acting!",
    "Service was okay, but the food was great"
])
print("Few-Shot Predictions (0=neg, 1=pos):", preds)

# ============================
# 5. Evaluation Section
# ============================
test_texts = ["Loved the product", "Worst purchase ever", "It was fine"]
test_labels = [1, 0, 0]

test_preds = trainer.model(test_texts)

print("Accuracy:", accuracy_score(test_labels, test_preds))
print("F1-score:", f1_score(test_labels, test_preds))
print("Confusion Matrix:\n", confusion_matrix(test_labels, test_preds))