# -*- coding: utf-8 -*-
"""Financial reasoning training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhjTny3OCROD3Y9nQzvsB98OUUIwXKkT
"""

# Cell 0 — Install required packages (run first)
!pip install -q transformers datasets accelerate sentencepiece evaluate rouge_score

# Cell 1 — Imports & config
import os
from pathlib import Path
import pandas as pd
import numpy as np
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    set_seed,
)
import evaluate

# Config
MODEL_ID = "t5-small"           # change to "google/flan-t5-base" if you prefer (needs more RAM)
OUTPUT_DIR = "t5_finance_qa"
CSV_PATH = "Financial_reasoning_dataset.csv"  # your CSV file
SEED = 42

NUM_EPOCHS = 6
LR = 5e-4
BATCH_SIZE = 8
MAX_SOURCE_LENGTH = 128
MAX_TARGET_LENGTH = 64
SAVE_STEPS = 500
set_seed(SEED)

print("torch:", torch.__version__, "cuda:", torch.cuda.is_available())

# Cell 2 — Safe CSV load (tries multiple encodings)
def read_csv_safely(path):
    encodings = ["utf-8", "utf-16", "utf-16le", "latin1", "ISO-8859-1", "cp1252"]
    last_err = None
    for enc in encodings:
        try:
            df = pd.read_csv(path, encoding=enc)
            print(f"Loaded CSV with encoding: {enc}")
            return df
        except Exception as e:
            last_err = e
            # continue trying
    raise ValueError(f"Unable to read CSV using tried encodings. Last error: {last_err}")

assert os.path.exists(CSV_PATH), f"CSV not found at {CSV_PATH}"
df = read_csv_safely(CSV_PATH)

# Cell 3 — Validate & normalize columns (Textual Question, Answer)
expected = ["Textual Question", "Answer"]
missing = [c for c in expected if c not in df.columns]
if missing:
    # try auto-detect / strip whitespace and case-insensitive match
    cols_map = {c: c.strip() for c in df.columns}
    # simple heuristics
    mapping = {}
    for col in df.columns:
        name = col.strip().lower()
        if "question" in name or "textual" in name or "prompt" in name:
            mapping[col] = "question"
        elif "answer" in name or "response" in name:
            mapping[col] = "answer"
    # If mapping found, rename and continue
    if mapping:
        df = df.rename(columns=mapping)
        print("Auto-renamed columns:", mapping)
    else:
        raise ValueError(f"Missing required columns: {missing}. Found columns: {df.columns.tolist()}")

# If we renamed to 'question' & 'answer' above, ensure we unify names:
if "Textual Question" in df.columns:
    df = df.rename(columns={"Textual Question": "question"})
elif "question" in df.columns:
    # already renamed
    pass
else:
    # if original had 'Textual Question' but case-diff, handled earlier - else raise
    raise ValueError("Could not find 'Textual Question' column. Columns: " + str(df.columns.tolist()))

if "Answer" in df.columns:
    df = df.rename(columns={"Answer": "answer"})
elif "answer" in df.columns:
    pass
else:
    raise ValueError("Could not find 'Answer' column. Columns: " + str(df.columns.tolist()))

# keep only required cols and drop empties
df = df[["question", "answer"]].astype(str)
df["question"] = df["question"].str.strip()
df["answer"] = df["answer"].str.strip()
df = df[(df["question"] != "") & (df["answer"] != "")].reset_index(drop=True)
assert len(df) > 0, "No valid rows after cleanup."

print("Dataset rows:", len(df))
print(df.head(3))

# Cell 4 — Train / Validation split -> HuggingFace Dataset
split_ratio = 0.85
train_end = int(len(df) * split_ratio)
train_df = df.iloc[:train_end].copy()
val_df = df.iloc[train_end:].copy()

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)
raw_ds = DatasetDict({"train": train_ds, "validation": val_ds})
print("Train size:", len(train_ds), "Val size:", len(val_ds))

# Cell 5 — Load tokenizer & model
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_ID)
print("Model & tokenizer loaded:", MODEL_ID)

# Cell 6 — Preprocess
def preprocess_batch(batch):
    inputs = [f"question: {q}" for q in batch["question"]]
    targets = batch["answer"]
    model_inputs = tokenizer(inputs, max_length=MAX_SOURCE_LENGTH, truncation=True, padding="max_length")
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets, max_length=MAX_TARGET_LENGTH, truncation=True, padding="max_length")["input_ids"]
    # mask pad tokens
    labels = [[(t if t != tokenizer.pad_token_id else -100) for t in seq] for seq in labels]
    model_inputs["labels"] = labels
    return model_inputs

tokenized = raw_ds.map(preprocess_batch, batched=True, remove_columns=raw_ds["train"].column_names)
print("Tokenization done.")

# Cell 7 — Data collator & TrainingArguments
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LR,
    logging_steps=50,
    save_steps=SAVE_STEPS,
    save_total_limit=2,
    fp16=torch.cuda.is_available(),
    predict_with_generate=False,   # avoid passing this to Trainer to maximize compatibility
    generation_max_length=MAX_TARGET_LENGTH,
    push_to_hub=False,
)

# Cell 8 — Trainer (no compute_metrics here)
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)
print("Trainer created.")

# Cell 9 — Train
trainer.train()
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training finished. Model saved to", OUTPUT_DIR)

# Cell 10 — Manual inference + ROUGE evaluation (uses rouge_score)
rouge_available = True
try:
    rouge = evaluate.load("rouge")
except Exception as e:
    print("ROUGE loading failed:", e)
    rouge_available = False

def generate_predictions(dataset, batch_size=8):
    preds = []
    refs = []
    model_device = next(model.parameters()).device
    model.eval()
    for i in range(0, len(dataset), batch_size):
        batch = dataset[i : i + batch_size]
        inputs = ["question: " + ex["question"] for ex in batch]
        enc = tokenizer(inputs, return_tensors="pt", truncation=True, padding=True).to(model_device)
        with torch.no_grad():
            out = model.generate(**enc, max_new_tokens=MAX_TARGET_LENGTH, num_beams=4)
        decoded = tokenizer.batch_decode(out, skip_special_tokens=True)
        preds.extend([d.strip() for d in decoded])
        refs.extend([ex["answer"].strip() for ex in batch])
    return preds, refs

print("Generating predictions on validation set...")
preds, refs = generate_predictions(val_df.to_dict("records"), batch_size=BATCH_SIZE)
print("Sample prediction:")
print("Q:", val_df.iloc[0]["question"])
print("PRED:", preds[0])
print("REF :", refs[0])

if rouge_available:
    results = rouge.compute(predictions=preds, references=refs, use_stemmer=True)
    print("ROUGE results (as fractions):", results)
    # print convenient percentages
    print({
        "rouge1": round(results["rouge1"] * 100, 2),
        "rouge2": round(results["rouge2"] * 100, 2),
        "rougeL": round(results["rougeL"] * 100, 2),
    })
else:
    # fallback simple exact-match and token overlap
    exact = sum(1 for p, r in zip(preds, refs) if p.strip().lower() == r.strip().lower()) / len(preds)
    print(f"Exact match (fallback): {exact:.3f}")

# Cell 11 — Inference helper
from transformers import pipeline
device = 0 if torch.cuda.is_available() else -1
pipe = pipeline("text2text-generation", model=OUTPUT_DIR, tokenizer=OUTPUT_DIR, device=device)

def answer_question(question_text, max_length=64):
    prompt = question_text if question_text.lower().startswith("question:") else "question: " + question_text
    out = pipe(prompt, max_length=max_length, do_sample=False, num_return_sequences=1)
    return out[0]["generated_text"]

# quick test
#print("Test inference:", answer_question("What is a balance sheet?"))