# -*- coding: utf-8 -*-
"""Financial reasoning training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhjTny3OCROD3Y9nQzvsB98OUUIwXKkT
"""

# If running on Colab, uncomment these:
!pip install -q transformers datasets accelerate sentencepiece evaluate

import os
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
)
import evaluate
import numpy as np

# -----------------------
# 1) Configs
# -----------------------
MODEL_ID = "t5-small"          # Small, fast, instruction-friendly for Q&A
OUTPUT_DIR = "t5_finance_qa"   # Where to save model checkpoints
SEED = 42

# -----------------------
# 2) Load and validate data
# -----------------------
csv_path = "finance_50_qa.csv"  # Ensure the CSV is present in the working dir

assert os.path.exists(csv_path), f"CSV file not found at {csv_path}"

df = pd.read_csv(csv_path)
# Expecting columns: 'question', 'answer'
required_cols = {"question", "answer"}
missing = required_cols - set(df.columns)
assert not missing, f"Missing required columns: {missing}"

# Basic cleanup: strip whitespace, drop empties
df["question"] = df["question"].astype(str).str.strip()
df["answer"] = df["answer"].astype(str).str.strip()
df = df[(df["question"] != "") & (df["answer"] != "")].reset_index(drop=True)
assert len(df) > 0, "No valid rows found after cleanup."

# -----------------------
# 3) Train/validation split
# -----------------------
# With only ~50 rows, keep validation small but present for sanity
split_ratio = 0.85
train_end = int(len(df) * split_ratio)

train_df = df.iloc[:train_end].copy()
val_df   = df.iloc[train_end:].copy()

train_ds = Dataset.from_pandas(train_df)
val_ds   = Dataset.from_pandas(val_df)
raw_ds   = DatasetDict({"train": train_ds, "validation": val_ds})

# -----------------------
# 4) Load tokenizer and model
# -----------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_ID)

# -----------------------
# 5) Preprocessing / tokenization
# -----------------------
# We’ll format inputs as "question: <text>" for T5-style tasks.
max_source_length = 128
max_target_length = 64

def preprocess_batch(batch):
    inputs = [f"question: {q}" for q in batch["question"]]
    targets = batch["answer"]

    model_inputs = tokenizer(
        inputs,
        max_length=max_source_length,
        truncation=True,
        padding="max_length",
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            targets,
            max_length=max_target_length,
            truncation=True,
            padding="max_length",
        )["input_ids"]

    # Replace pad token ids in labels with -100 to ignore during loss
    labels = [
        [(token if token != tokenizer.pad_token_id else -100) for token in label_seq]
        for label_seq in labels
    ]

    model_inputs["labels"] = labels
    return model_inputs

tokenized_ds = raw_ds.map(
    preprocess_batch,
    batched=True,
    remove_columns=raw_ds["train"].column_names,
)

# -----------------------
# 6) Data collator
# -----------------------
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

# -----------------------
# 7) Metrics (optional, ROUGE for text quality)
# -----------------------
rouge = evaluate.load("rouge")

def postprocess_text(preds, labels):
    preds = [p.strip() for p in preds]
    labels = [l.strip() for l in labels]
    return preds, labels

def compute_metrics(eval_pred):
    preds, labels = eval_pred
    # Decode predictions
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    # Replace -100 in labels to pad_token_id before decoding
    label_ids = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)
    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
        use_stemmer=True
    )
    # Return some concise metrics
    return {
        "rouge1": round(result["rouge1"] * 100, 2),
        "rouge2": round(result["rouge2"] * 100, 2),
        "rougeL": round(result["rougeL"] * 100, 2),
    }

# -----------------------
# 8) Training args
# -----------------------
# Light settings suitable for a tiny dataset; adjust if you want longer training.
training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,
    do_eval=True,                      # Enables evaluation
    save_steps=500,                    # Save every 500 steps (adjust as needed)
    eval_steps=500,                    # Evaluate every 500 steps
    logging_steps=10,
    learning_rate=5e-4,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=20,
    weight_decay=0.0,
    predict_with_generate=True,
    generation_max_length=64,
    seed=SEED,
    push_to_hub=False,
    report_to=[],
)

# -----------------------
# 9) Trainer
# -----------------------
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# -----------------------
# 10) Train and save
# -----------------------
train_result = trainer.train()
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# -----------------------
# 11) Quick inference
# -----------------------
def answer_question(question, max_new_tokens=64):
    input_text = f"question: {question}"
    inputs = tokenizer(input_text, return_tensors="pt")
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        num_beams=4,
        no_repeat_ngram_size=2,
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Test a few samples
#test_questions = [
    #"What is a balance sheet?",
    #"What is GDP?",
    #"What is an options contract?",
#]
#for q in test_questions:
    #print(f"Q: {q}")
    #print(f"A: {answer_question(q)}\n")

print("Training complete. Model saved to:", OUTPUT_DIR)