# -*- coding: utf-8 -*-
"""oneshot_testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8tNi2j8KEKwEa2A0eMxc5pF6dMb1zCK

Install Required Libraries
"""

!pip install transformers datasets accelerate setfit torch

"""promt based: Sentiment Classification (One-Shot)"""

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = """Classify sentiment:
Text: I love this movie! -> Positive
Text: The spacyr code was really difficult to debug from scratch ->"""

result = generator(prompt, max_length=50)
print(result[0]['generated_text'])

"""One-Shot with SetFit (Training-Based)"""

from setfit import SetFitModel, SetFitTrainer
from datasets import Dataset

# Load pretrained Sentence Transformer
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")

# One-shot dataset: one example per class
train_dataset = Dataset.from_dict({
    "text": ["I love this!", "This is bad."],
    "label": [1, 0]  # 1=Positive, 0=Negative
})

trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    num_iterations=20,
    batch_size=16,
    num_epochs=1
)

trainer.train()

# Test prediction
print(trainer.model(["The movie was boring", "Amazing performance!"]))

from setfit import SetFitModel, SetFitTrainer
from datasets import Dataset

# Load pretrained Sentence Transformer
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")

# One-shot dataset: one example per class
train_dataset = Dataset.from_dict({
    "text": ["I love this!", "This is bad."],
    "label": [1, 0]  # 1=Positive, 0=Negative
})

trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    num_iterations=20,
    batch_size=16,
    num_epochs=1
)

trainer.train()

# Test prediction
print(trainer.model(["The movie was boring", "Amazing performance!"]))

from setfit import Trainer

from setfit import SetFitModel, SetFitTrainer
from datasets import Dataset

# Load pretrained Sentence Transformer
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-mpnet-base-v2")

# One-shot dataset: one example per class
train_dataset = Dataset.from_dict({
    "text": ["I love this!", "This is bad."],
    "label": [1, 0]  # 1=Positive, 0=Negative
})

trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    num_iterations=20,
    batch_size=16,
    num_epochs=1
)

trainer.train()

# Test prediction
print(trainer.model(["The movie was boring", "Amazing performance!"]))