# -*- coding: utf-8 -*-
"""Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ouo0Vl-D8TE_uzbOlCJjqhKyzU_tO8sw

training model
"""

# ============================
# 1. Install Required Libraries
# ============================
!pip install -q transformers datasets setfit torch accelerate scikit-learn pandas

# ============================
# 2. Load Dataset (CSV/Excel)
# ============================
import pandas as pd
from datasets import Dataset
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Load your dataset
df = pd.read_csv("Financial_dataset.csv")   # or pd.read_excel("financial_dataset.xlsx")

# Expected columns: question, answer, language, type
print("Sample rows:\n", df.head())

# Convert answers into categorical labels
le = LabelEncoder()
df["label"] = le.fit_transform(df["answer"])  # numeric labels for classification

# Convert to Hugging Face Dataset
dataset = Dataset.from_pandas(df[["question", "label", "language", "type"]])

# Split into train/test
dataset = dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = dataset["train"]
test_dataset = dataset["test"]

# ============================
# 3. Few-Shot Training with SetFit v2
# ============================
from setfit import SetFitModel, Trainer, TrainingArguments

# Load multilingual backbone
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# Training arguments
args = TrainingArguments(
    output_dir="checkpoints",
    batch_size=(16, 2),
    num_epochs=(1, 16),
    num_iterations=20,
    body_learning_rate=2e-5,
    head_learning_rate=1e-2,
    use_amp=False
)

# Trainer with column mapping
trainer = Trainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    args=args,
    metric="accuracy",
    column_mapping={"question": "text", "label": "label"}
)

# Train
trainer.train()

# ============================
# 4. Global Evaluation
# ============================
y_true = test_dataset["label"]
y_pred = trainer.model(test_dataset["question"])

print("Global Accuracy:", accuracy_score(y_true, y_pred))
print("Global F1-score:", f1_score(y_true, y_pred, average="weighted"))
print("Global Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

# ============================
# 5. Language-Wise Evaluation
# ============================
languages = df["language"].unique()

for lang in languages:
    subset = test_dataset.filter(lambda x: x["language"] == lang)
    if len(subset) == 0:
        continue

    y_true_lang = subset["label"]
    y_pred_lang = trainer.model(subset["question"])

    print(f"\n--- {lang} ---")
    print("Accuracy:", accuracy_score(y_true_lang, y_pred_lang))
    print("F1-score:", f1_score(y_true_lang, y_pred_lang, average="weighted"))
    print("Confusion Matrix:\n", confusion_matrix(y_true_lang, y_pred_lang))

"""testing 2"""

# ============================
# 1. Install Required Libraries
# ============================
!pip install -q transformers datasets setfit torch accelerate scikit-learn pandas

# ============================
# 2. Load Dataset (CSV/Excel)
# ============================
import pandas as pd
from datasets import Dataset
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Load your dataset
df = pd.read_csv("Financial_dataset.csv")   # or pd.read_excel("financial_dataset.xlsx")

# Expected columns: question, answer, language, type
print("Sample rows:\n", df.head())

# Convert 'type' into categorical labels (classification target)
le = LabelEncoder()
df["label"] = le.fit_transform(df["type"])  # e.g. GST=0, Interest=1, Discount=2

# Convert to Hugging Face Dataset
dataset = Dataset.from_pandas(df[["question", "label", "language", "type"]])

# Split into train/test
dataset = dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = dataset["train"]
test_dataset = dataset["test"]

# ============================
# 3. Few-Shot Training with SetFit v2
# ============================
from setfit import SetFitModel, Trainer, TrainingArguments

# Load multilingual backbone
model = SetFitModel.from_pretrained("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# Training arguments
args = TrainingArguments(
    output_dir="checkpoints",
    batch_size=(16, 2),
    num_epochs=(1, 16),
    num_iterations=20,
    body_learning_rate=2e-5,
    head_learning_rate=1e-2,
    use_amp=False
)

# Trainer with column mapping
trainer = Trainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    args=args,
    metric="accuracy",
    column_mapping={"question": "text", "label": "label"}
)

# Train
trainer.train()

# ============================
# 4. Global Evaluation
# ============================
y_true = test_dataset["label"]
y_pred = trainer.model(test_dataset["question"])

print("Global Accuracy:", accuracy_score(y_true, y_pred))
print("Global F1-score:", f1_score(y_true, y_pred, average="weighted"))
print("Global Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

# ============================
# 5. Language-Wise Evaluation
# ============================
languages = df["language"].unique()

for lang in languages:
    subset = test_dataset.filter(lambda x: x["language"] == lang)
    if len(subset) == 0:
        continue

    y_true_lang = subset["label"]
    y_pred_lang = trainer.model(subset["question"])

    print(f"\n--- {lang} ---")
    print("Accuracy:", accuracy_score(y_true_lang, y_pred_lang))
    print("F1-score:", f1_score(y_true_lang, y_pred_lang, average="weighted"))
    print("Confusion Matrix:\n", confusion_matrix(y_true_lang, y_pred_lang))