# -*- coding: utf-8 -*-
"""Zeroshot testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFmds9FRSk1oOVOoAURWm9pxXLxN2OOO

Install Required Libraries
"""

!pip install transformers datasets accelerate setfit torch

"""Authenticating with Hugging Face Hub"""

from huggingface_hub import notebook_login
notebook_login()

"""Loading a Zero-Shot Pipeline"""

from transformers import pipeline

classifier = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli")

"""Runing Zero-Shot Classification"""

sequence = "This movie was absolutely wonderful and inspiring."
labels = ["positive", "negative", "neutral"]

result = classifier(sequence, candidate_labels=labels)
print(result)

sequence = "the pyspark code was  really difficult to debug from scrach"
labels = ["positive", "negative", "neutral"]

result = classifier(sequence, candidate_labels=labels)
print(result)

sequence = "The scool boy met with an seriou accident while crossing the road"
labels = ["positive", "negative", "neutral"]

result = classifier(sequence, candidate_labels=labels)
print(result)

"""Sentiment analysis - testing"""

sequence = "The food was absolutely delicious and the service was excellent."
labels = ["positive", "negative", "neutral"]

result = classifier(sequence, candidate_labels=labels)
print(result)

"""Topic Classification - testing"""

sequence = "The government announced new policies on renewable energy."
labels = ["politics", "sports", "technology", "health"]

result = classifier(sequence, candidate_labels=labels)
print(result)

"""Intent detection -  testing"""

sequence = "Can you tell me the balance of my account?"
labels = ["check_balance", "transfer_money", "open_account", "general_query"]

result = classifier(sequence, candidate_labels=labels)
print(result)